[build]
  publish   = "."
  functions = "netlify/functions"
  command   = "echo static"

[[redirects]]
  from = "/s/:id"
  to   = "/index.html"
  status = 200

[[redirects]]
  from = "/api/share"
  to   = "/.netlify/functions/share_api"
  status = 200

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
