[build]
  base = "lottie-preview"
  publish = "."
  functions = "netlify/functions"
  # Вариант А: без команды (статический сайт)
  # command = ""
  # Вариант Б: явный no-op
  command = "echo static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/s/:id"
  to = "/?id=:id"
  status = 200
