[build]
  publish   = "lottie-preview"
  functions = "lottie-preview/netlify/functions"
  command   = "echo static"

# Короткая ссылка рендерит index.html
[[redirects]]
  from = "/s/:id"
  to   = "/index.html"
  status = 200

# Явное сопоставление /api/share -> /.netlify/functions/share_api
[[redirects]]
  from = "/api/share"
  to   = "/.netlify/functions/share_api"
  status = 200

# Остальные функции по шаблону (например /api/shot)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# (опционально) если вдруг кто-то обращается к исходнику функции как статике —
# перебрасываем в рантайм
[[redirects]]
  from = "/netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
